import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"

const root = process.cwd()

function read(file) {
  return fs.readFileSync(path.join(root, file), "utf8")
}

test("mobile navbar, search and product cards keep the simplified mobile UX", () => {
  const navbar = read("src/components/Navbar.tsx")
  const mobileSheet = read("src/components/mobile/MobileSheet.tsx")
  const bodyScrollLock = read("src/hooks/useBodyScrollLock.ts")
  const productCard = read("src/shop/components/ProductCard.tsx")
  const homeShop = read("src/sections/HomeShop.tsx")
  const canHoverHook = read("src/hooks/useCanHover.ts")
  const cartPage = read("src/shop/pages/ShopCartPage.tsx")
  const registerPage = read("src/shop/pages/ShopRegisterPage.tsx")
  const authRoutes = read("src/server/shop/routes/authRoutes.mjs")
  const styles = read("src/styles.css")

  assert.match(navbar, /label: "Home"/)
  assert.match(navbar, /label: "Categorie"/)
  assert.match(navbar, /label: "Collezioni"/)
  assert.match(navbar, /label: "Catalogo"/)
  assert.match(navbar, /label: "Recensioni"/)
  assert.match(navbar, /label: "Ordini"/)
  assert.doesNotMatch(navbar, /Privacy \/ info/)
  assert.match(navbar, /if \(isMobileViewport\) \{/)
  assert.match(navbar, /navigate\("\/shop\/cart"\)/)
  assert.match(navbar, /if \(step === "register"\)/)
  assert.match(navbar, /if \(detail\?\.step === "register"\)/)
  assert.match(navbar, /navigate\("\/shop\/account"\)/)
  assert.doesNotMatch(navbar, /setProfileStep\("register"\)/)
  assert.match(navbar, /mobileScrollablePanelClass/)
  assert.match(navbar, /mobileSheetFooterClass/)
  assert.match(navbar, /useIsMobileViewport/)
  assert.match(navbar, /isMobileViewport \?/)
  assert.match(navbar, /shouldUseGlobalOverlayLock/)
  assert.match(navbar, /<MobileSheet/)
  assert.match(navbar, /onWheelCapture=\{containWheel\}/)
  assert.match(mobileSheet, /useBodyScrollLock/)
  assert.match(mobileSheet, /h-\[calc\(100svh-0.75rem\)\]/)
  assert.match(mobileSheet, /overflow-y-auto/)
  assert.match(mobileSheet, /shrink-0 border-t/)
  assert.match(bodyScrollLock, /position = "fixed"/)
  assert.match(navbar, /data-testid="mobile-search-suggestions"/)
  assert.match(navbar, /data-testid="mobile-search-live-results"/)
  assert.match(navbar, /touch-pan-x/)
  assert.match(navbar, /useCanHover/)
  assert.match(productCard, /useCanHover/)
  assert.match(productCard, /secondaryImage/)
  assert.match(productCard, /group-hover:opacity-100/)
  assert.match(canHoverHook, /hover: hover/)
  assert.match(homeShop, /id="shop-categories"/)
  assert.match(homeShop, /id="shop-collections"/)
  assert.match(homeShop, /id="shop-catalog"/)
  assert.match(cartPage, /title=\{isMobileViewport \? "Carrello" : "Riepilogo ordine"\}/)
  assert.match(cartPage, /Quantità/)
  assert.match(cartPage, /Aumenta quantità/)
  assert.match(cartPage, /Diminuisci quantità/)
  assert.match(styles, /@media \(max-width: 767px\)/)
  assert.match(styles, /font-size: 16px;/)
  assert.match(registerPage, /Pagina \{step\} di 3/)
  assert.match(registerPage, /Dati personali/)
  assert.match(registerPage, /Indirizzo spedizione/)
  assert.match(registerPage, /Sicurezza account/)
  assert.match(registerPage, /Salva modifiche/)
  assert.match(registerPage, /shippingAddressLine1/)
  assert.match(registerPage, /shippingStreetNumber/)
  assert.match(registerPage, /shippingPostalCode/)
  assert.match(authRoutes, /shippingCountry/)
  assert.match(authRoutes, /shippingAddressLine1/)
  assert.match(cartPage, /title=\{isMobileViewport \? "Carrello" : "Riepilogo ordine"\}/)
})
