import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"

const root = process.cwd()

function read(file) {
  return fs.readFileSync(path.join(root, file), "utf8")
}

test("mobile navbar, search and product cards keep the simplified mobile UX", () => {
  const navbar = read("src/components/Navbar.tsx")
  const horizontalRail = read("src/components/HorizontalScrollRail.tsx")
  const mobileSheet = read("src/components/mobile/MobileSheet.tsx")
  const bodyScrollLock = read("src/hooks/useBodyScrollLock.ts")
  const productCard = read("src/shop/components/ProductCard.tsx")
  const homeShop = read("src/sections/HomeShop.tsx")
  const canHoverHook = read("src/hooks/useCanHover.ts")
  const cartPage = read("src/shop/pages/ShopCartPage.tsx")
  const registerPage = read("src/shop/pages/ShopRegisterPage.tsx")
  const authRoutes = read("src/server/shop/routes/authRoutes.mjs")
  const adminRoutes = read("src/server/shop/routes/adminRoutes.mjs")
  const adminUsersSection = read("src/shop/components/admin/AdminUsersSection.tsx")
  const styles = read("src/styles.css")

  assert.match(navbar, /label: "Home"/)
  assert.match(navbar, /label: "Categorie"/)
  assert.match(navbar, /label: "Collezioni"/)
  assert.match(navbar, /label: "Catalogo"/)
  assert.match(navbar, /label: "Recensioni"/)
  assert.match(navbar, /label: "Ordini"/)
  assert.doesNotMatch(navbar, /Privacy \/ info/)
  assert.doesNotMatch(navbar, /mt-1 block text-xs text-white\/55/)
  assert.match(navbar, /if \(isMobileViewport\) \{/)
  assert.match(navbar, /navigate\("\/shop\/cart"\)/)
  assert.match(navbar, /if \(step === "register"\)/)
  assert.match(navbar, /if \(detail\?\.step === "register"\)/)
  assert.match(navbar, /navigate\("\/shop\/account"\)/)
  assert.match(navbar, /requestedStep === "login" \? "login" : "initial"/)
  assert.match(navbar, /requestedStepFromState === "login" \|\| requestedStep === "login"/)
  assert.doesNotMatch(navbar, /setProfileStep\("register"\)/)
  assert.match(navbar, /mobileScrollablePanelClass/)
  assert.match(navbar, /mobileSheetFooterClass/)
  assert.match(navbar, /useIsMobileViewport/)
  assert.match(navbar, /isMobileViewport \?/)
  assert.match(navbar, /shouldUseGlobalOverlayLock/)
  assert.match(navbar, /<MobileSheet/)
  assert.match(navbar, /onWheelCapture=\{containWheel\}/)
  assert.match(mobileSheet, /useBodyScrollLock/)
  assert.match(mobileSheet, /h-\[calc\(100svh-0.75rem\)\]/)
  assert.match(mobileSheet, /overflow-y-auto/)
  assert.match(mobileSheet, /shrink-0 border-t/)
  assert.match(bodyScrollLock, /position = "fixed"/)
  assert.match(navbar, /data-testid="mobile-search-suggestions"/)
  assert.match(navbar, /data-testid="mobile-search-live-results"/)
  assert.match(navbar, /data-testid="desktop-search-suggestions"/)
  assert.match(navbar, /data-testid="desktop-search-live-results"/)
  assert.match(navbar, /className="relative hidden md:block"/)
  assert.match(navbar, /ref=\{searchRootRef\} className="min-w-0"/)
  assert.match(navbar, /absolute left-0 right-0 top-full/)
  assert.match(navbar, /searchOpen && !isMobileViewport/)
  assert.match(navbar, /searchOpen && isMobileViewport/)
  assert.match(navbar, /isMobileViewport && searchOpen/)
  assert.match(navbar, /if \(!searchOpen \|\| isMobileViewport\) return/)
  assert.match(navbar, /event\.key === "Escape"/)
  assert.match(navbar, /searchRootRef\.current\?\.contains\(target\) \|\| overlayRef\.current\?\.contains\(target\)/)
  assert.match(navbar, /HorizontalScrollRail/)
  assert.match(navbar, /touch-pan-x/)
  assert.match(navbar, /event\.preventDefault\(\)/)
  assert.match(navbar, /event\.stopPropagation\(\)/)
  assert.match(navbar, /target\.scrollLeft \+= delta/)
  assert.match(horizontalRail, /onWheelCapture=\{onWheel\}/)
  assert.match(navbar, /useCanHover/)
  assert.match(productCard, /useCanHover/)
  assert.match(productCard, /secondaryImage/)
  assert.match(productCard, /group-hover:opacity-100/)
  assert.match(canHoverHook, /hover: hover/)
  assert.match(homeShop, /id="shop-categories"/)
  assert.match(homeShop, /id="shop-collections"/)
  assert.match(homeShop, /id="shop-catalog"/)
  assert.match(homeShop, /HorizontalScrollRail/)
  assert.match(cartPage, /title=\{isMobileViewport \? "Carrello" : "Riepilogo ordine"\}/)
  assert.match(cartPage, /Quantità/)
  assert.match(cartPage, /Aumenta quantità/)
  assert.match(cartPage, /Diminuisci quantità/)
  assert.match(styles, /@media \(max-width: 767px\)/)
  assert.match(styles, /font-size: 16px;/)
  assert.match(registerPage, /Pagina \{step\} di 3/)
  assert.match(registerPage, /Dati personali/)
  assert.match(registerPage, /Indirizzo spedizione/)
  assert.match(registerPage, /Sicurezza account/)
  assert.match(registerPage, /Modifica profilo/)
  assert.match(registerPage, /Conferma email/)
  assert.match(registerPage, /Nuova password \(opzionale\)/)
  assert.match(registerPage, /Indietro/)
  assert.match(registerPage, /Salva/)
  assert.match(registerPage, /state=\{\{ openProfileStep: "login" \}\}/)
  assert.match(registerPage, /shippingAddressLine1/)
  assert.match(registerPage, /shippingStreetNumber/)
  assert.match(registerPage, /shippingPostalCode/)
  const authPage = read("src/shop/pages/ShopAuthPage.tsx")
  assert.match(authPage, /\?profile=open&step=login/)
  assert.match(authPage, /Reindirizzamento login/)
  assert.match(authRoutes, /shippingCountry/)
  assert.match(authRoutes, /shippingAddressLine1/)
  assert.match(cartPage, /title=\{isMobileViewport \? "Carrello" : "Riepilogo ordine"\}/)
  assert.match(horizontalRail, /canScrollRight/)
  assert.match(horizontalRail, /canScrollLeft/)
  assert.match(horizontalRail, /aria-label=\{ariaLabel\}/)
  assert.match(horizontalRail, /aria-label="Scorri a sinistra"/)
  assert.match(horizontalRail, /node\.scrollBy\(\{ left: delta, behavior: "smooth" \}\)/)
  assert.match(horizontalRail, /absolute inset-y-0 left-2 z-10 flex items-center/)
  assert.match(horizontalRail, /absolute inset-y-0 right-2 z-10 flex items-center/)
  assert.match(adminUsersSection, /Cerca per username o email/)
  assert.match(adminUsersSection, /Ordina per/)
  assert.match(adminUsersSection, /Username A-Z/)
  assert.match(adminUsersSection, /Data creazione crescente/)
  assert.match(adminUsersSection, /Data creazione decrescente/)
  assert.match(adminUsersSection, /sortBy/)
  assert.match(adminUsersSection, /Rendi admin/)
  assert.match(adminUsersSection, /Rendi cliente/)
  assert.match(adminUsersSection, /ConfirmActionModal/)
  assert.match(adminUsersSection, /getButtonClassName\(\{ variant: "cart", size: "sm" \}\)/)
  assert.match(adminUsersSection, /loadingLabel="In corso\.\.\."/)
  assert.match(adminUsersSection, /confirmVariant="cart"/)
  assert.match(adminRoutes, /"\/users\/:id\/role"/)
  assert.match(adminRoutes, /z\.enum\(\["admin", "customer"\]\)/)
  assert.match(adminRoutes, /Impossibile rimuovere l'ultimo admin/)
})
